export const defaultJavaCode =
  '/*********************************************************************************************\nWelcome👏 to PeerCoder🎯🧑🏻‍🤝‍🧑\nPeerCoder is a real-time⌛ collaboration platform📌 that enables live video/audio📽️🎧🎙️ coding, where \nyou can invite and connect🤝 with other peers and Practise🏋️‍♀️ Coding to prepare for the interviews\nand exams in the various popular coding languages like C, C++, Python, Java\nBrainstorm coding problems together with peers through video chat anwhere in the world🌏.\nHappy Coding🍵🧑‍💻\n©️ Designed and Developed by Ashish Sharma😊 (Linkedin: https://linkedin.com/in/aeshtech)\n*********************************************************************************************/\n\npublic class Main {\n  public static void main(String[] args) {\n    System.out.println("Hello World");\n  }\n}';

export const defaultPythonCode = `'''*********************************************************************************************\nWelcome to PeerCoder\nPeerCoder is a real-time collaboration platform that enables live video/audio coding, where \nyou can invite and connect with other peers and Practise Coding to prepare for the interviews\nand exams in the various popular coding languages like C, C++, Python, Java\nBrainstorm coding problems together with peers through video chat anwhere in the world.\nHappy Coding :)\nDesigned and Developed by Ashish Sharma (Linkedin: https://linkedin.com/in/aeshtech)\n*********************************************************************************************'''\n\nprint("Hello World")`;

export const defaultCCode =
  '/*********************************************************************************************\nWelcome👏 to PeerCoder🎯🧑🏻‍🤝‍🧑\nPeerCoder is a real-time⌛ collaboration platform📌 that enables live video/audio📽️🎧🎙️ coding, where \nyou can invite and connect🤝 with other peers and Practise🏋️‍♀️ Coding to prepare for the interviews\nand exams in the various popular coding languages like C, C++, Python, Java\nBrainstorm coding problems together with peers through video chat anwhere in the world🌏.\nHappy Coding🍵🧑‍💻\n©️ Designed and Developed by Ashish Sharma😊 (Linkedin: https://linkedin.com/in/aeshtech)\n*********************************************************************************************/\n\n#include <stdio.h>\n\nint main(){\n    printf("Hello World");\n    return 0;\n}';

export const defaultCPPCode =
  '/*********************************************************************************************\nWelcome👏 to PeerCoder🎯🧑🏻‍🤝‍🧑\nPeerCoder is a real-time⌛ collaboration platform📌 that enables live video/audio📽️🎧🎙️ coding, where \nyou can invite and connect🤝 with other peers and Practise🏋️‍♀️ Coding to prepare for the interviews\nand exams in the various popular coding languages like C, C++, Python, Java\nBrainstorm coding problems together with peers through video chat anwhere in the world🌏.\nHappy Coding🍵🧑‍💻\n©️ Designed and Developed by Ashish Sharma😊 (Linkedin: https://linkedin.com/in/aeshtech)\n*********************************************************************************************/\n\n#include <iostream>\n\nint main()\n{\n  std::cout<<"Hello World C++";\n  return 0;\n}';
export const defaultJSCode = `/*********************************************************************************************
Welcome👏 to PeerCoder🎯🧑🏻‍🤝‍🧑
PeerCoder is a real-time⌛ collaboration platform📌 that enables live video/audio📽️🎧🎙️ coding, where 
you can invite and connect🤝 with other peers and Practise🏋️‍♀️ Coding to prepare for the interviews
and exams in the various popular coding languages like C, C++, Python, Java
Brainstorm coding problems together with peers through video chat anwhere in the world🌏.
Happy Coding🍵🧑‍💻
©️ Designed and Developed by Ashish Sharma😊 (Linkedin: https://linkedin.com/in/aeshtech)
*********************************************************************************************/

console.log("Hello World Javascript");` 